name = "SINNLS"
uuid = "93fee547-677c-4488-936b-98036d057900"
authors = ["Jelena Diakonikolas <jelena@cs.wisc.edu>",
	   "Swati Padmanabhan <pswati@uw.edu>",
           "Chenghui Li <cli539@wisc.edu>",
           "Chaobing Song <chaobing.song@wisc.edu>"]
version = "0.1.0"

[deps]
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
